# Generated by Django 5.0.1 on 2024-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chataccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='chataccount',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
