# Generated by Django 5.0.1 on 2024-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatprivateroom_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unseenchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
