# Generated by Django 5.0.1 on 2024-01-19 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatpublic', '0002_alter_publicchatroom_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicChatRoom',
            new_name='ChatPublicRoom',
        ),
        migrations.RenameModel(
            old_name='PublicRoomChatMessage',
            new_name='ChatPublicRoomMessage',
        ),
    ]
