# Generated by Django 5.0.1 on 2024-01-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friendsrequest_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendsrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
        migrations.DeleteModel(
            name='FriendsRequest',
        ),
    ]
