# Generated by Django 5.0.1 on 2024-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_remove_friendsrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
